/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface webviewConstants {
  public final static int WEBVIEW_HINT_NONE = webviewJNI.WEBVIEW_HINT_NONE_get();
  public final static int WEBVIEW_HINT_MIN = webviewJNI.WEBVIEW_HINT_MIN_get();
  public final static int WEBVIEW_HINT_MAX = webviewJNI.WEBVIEW_HINT_MAX_get();
  public final static int WEBVIEW_HINT_FIXED = webviewJNI.WEBVIEW_HINT_FIXED_get();
}
