/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class webview implements webviewConstants {
  public static SWIGTYPE_p_void webview_create(int debug, SWIGTYPE_p_void window) {
    long cPtr = webviewJNI.webview_create(debug, SWIGTYPE_p_void.getCPtr(window));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void webview_destroy(SWIGTYPE_p_void w) {
    webviewJNI.webview_destroy(SWIGTYPE_p_void.getCPtr(w));
  }

  public static void webview_run(SWIGTYPE_p_void w) {
    webviewJNI.webview_run(SWIGTYPE_p_void.getCPtr(w));
  }

  public static void webview_terminate(SWIGTYPE_p_void w) {
    webviewJNI.webview_terminate(SWIGTYPE_p_void.getCPtr(w));
  }

  public static void webview_dispatch(SWIGTYPE_p_void w, SWIGTYPE_p_f_p_void_p_void__void fn, SWIGTYPE_p_void arg) {
    webviewJNI.webview_dispatch(SWIGTYPE_p_void.getCPtr(w), SWIGTYPE_p_f_p_void_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(arg));
  }

  public static SWIGTYPE_p_void webview_get_window(SWIGTYPE_p_void w) {
    long cPtr = webviewJNI.webview_get_window(SWIGTYPE_p_void.getCPtr(w));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void webview_set_title(SWIGTYPE_p_void w, String title) {
    webviewJNI.webview_set_title(SWIGTYPE_p_void.getCPtr(w), title);
  }

  public static void webview_set_size(SWIGTYPE_p_void w, int width, int height, int hints) {
    webviewJNI.webview_set_size(SWIGTYPE_p_void.getCPtr(w), width, height, hints);
  }

  public static void webview_navigate(SWIGTYPE_p_void w, String url) {
    webviewJNI.webview_navigate(SWIGTYPE_p_void.getCPtr(w), url);
  }

  public static void webview_set_html(SWIGTYPE_p_void w, String html) {
    webviewJNI.webview_set_html(SWIGTYPE_p_void.getCPtr(w), html);
  }

  public static void webview_init(SWIGTYPE_p_void w, String js) {
    webviewJNI.webview_init(SWIGTYPE_p_void.getCPtr(w), js);
  }

  public static void webview_eval(SWIGTYPE_p_void w, String js) {
    webviewJNI.webview_eval(SWIGTYPE_p_void.getCPtr(w), js);
  }

  public static void webview_bind(SWIGTYPE_p_void w, String name, SWIGTYPE_p_f_p_q_const__char_p_q_const__char_p_void__void fn, SWIGTYPE_p_void arg) {
    webviewJNI.webview_bind(SWIGTYPE_p_void.getCPtr(w), name, SWIGTYPE_p_f_p_q_const__char_p_q_const__char_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(arg));
  }

  public static void webview_unbind(SWIGTYPE_p_void w, String name) {
    webviewJNI.webview_unbind(SWIGTYPE_p_void.getCPtr(w), name);
  }

  public static void webview_return(SWIGTYPE_p_void w, String seq, int status, String result) {
    webviewJNI.webview_return(SWIGTYPE_p_void.getCPtr(w), seq, status, result);
  }

}
