/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class webviewJNI {
  public final static native int WEBVIEW_HINT_NONE_get();
  public final static native int WEBVIEW_HINT_MIN_get();
  public final static native int WEBVIEW_HINT_MAX_get();
  public final static native int WEBVIEW_HINT_FIXED_get();
  public final static native long webview_create(int jarg1, long jarg2);
  public final static native void webview_destroy(long jarg1);
  public final static native void webview_run(long jarg1);
  public final static native void webview_terminate(long jarg1);
  public final static native void webview_dispatch(long jarg1, long jarg2, long jarg3);
  public final static native long webview_get_window(long jarg1);
  public final static native void webview_set_title(long jarg1, String jarg2);
  public final static native void webview_set_size(long jarg1, int jarg2, int jarg3, int jarg4);
  public final static native void webview_navigate(long jarg1, String jarg2);
  public final static native void webview_set_html(long jarg1, String jarg2);
  public final static native void webview_init(long jarg1, String jarg2);
  public final static native void webview_eval(long jarg1, String jarg2);
  public final static native void webview_bind(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native void webview_unbind(long jarg1, String jarg2);
  public final static native void webview_return(long jarg1, String jarg2, int jarg3, String jarg4);
}
