//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class webview {
  public static SWIGTYPE_p_void webview_create(int debug, SWIGTYPE_p_void window) {
    global::System.IntPtr cPtr = webviewPINVOKE.webview_create(debug, SWIGTYPE_p_void.getCPtr(window));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public static void webview_destroy(SWIGTYPE_p_void w) {
    webviewPINVOKE.webview_destroy(SWIGTYPE_p_void.getCPtr(w));
  }

  public static void webview_run(SWIGTYPE_p_void w) {
    webviewPINVOKE.webview_run(SWIGTYPE_p_void.getCPtr(w));
  }

  public static void webview_terminate(SWIGTYPE_p_void w) {
    webviewPINVOKE.webview_terminate(SWIGTYPE_p_void.getCPtr(w));
  }

  public static void webview_dispatch(SWIGTYPE_p_void w, SWIGTYPE_p_f_p_void_p_void__void fn, SWIGTYPE_p_void arg) {
    webviewPINVOKE.webview_dispatch(SWIGTYPE_p_void.getCPtr(w), SWIGTYPE_p_f_p_void_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(arg));
  }

  public static SWIGTYPE_p_void webview_get_window(SWIGTYPE_p_void w) {
    global::System.IntPtr cPtr = webviewPINVOKE.webview_get_window(SWIGTYPE_p_void.getCPtr(w));
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public static void webview_set_title(SWIGTYPE_p_void w, string title) {
    webviewPINVOKE.webview_set_title(SWIGTYPE_p_void.getCPtr(w), title);
  }

  public static void webview_set_size(SWIGTYPE_p_void w, int width, int height, int hints) {
    webviewPINVOKE.webview_set_size(SWIGTYPE_p_void.getCPtr(w), width, height, hints);
  }

  public static void webview_navigate(SWIGTYPE_p_void w, string url) {
    webviewPINVOKE.webview_navigate(SWIGTYPE_p_void.getCPtr(w), url);
  }

  public static void webview_set_html(SWIGTYPE_p_void w, string html) {
    webviewPINVOKE.webview_set_html(SWIGTYPE_p_void.getCPtr(w), html);
  }

  public static void webview_init(SWIGTYPE_p_void w, string js) {
    webviewPINVOKE.webview_init(SWIGTYPE_p_void.getCPtr(w), js);
  }

  public static void webview_eval(SWIGTYPE_p_void w, string js) {
    webviewPINVOKE.webview_eval(SWIGTYPE_p_void.getCPtr(w), js);
  }

  public static void webview_bind(SWIGTYPE_p_void w, string name, SWIGTYPE_p_f_p_q_const__char_p_q_const__char_p_void__void fn, SWIGTYPE_p_void arg) {
    webviewPINVOKE.webview_bind(SWIGTYPE_p_void.getCPtr(w), name, SWIGTYPE_p_f_p_q_const__char_p_q_const__char_p_void__void.getCPtr(fn), SWIGTYPE_p_void.getCPtr(arg));
  }

  public static void webview_unbind(SWIGTYPE_p_void w, string name) {
    webviewPINVOKE.webview_unbind(SWIGTYPE_p_void.getCPtr(w), name);
  }

  public static void webview_return(SWIGTYPE_p_void w, string seq, int status, string result) {
    webviewPINVOKE.webview_return(SWIGTYPE_p_void.getCPtr(w), seq, status, result);
  }

  public static readonly int WEBVIEW_HINT_NONE = webviewPINVOKE.WEBVIEW_HINT_NONE_get();
  public static readonly int WEBVIEW_HINT_MIN = webviewPINVOKE.WEBVIEW_HINT_MIN_get();
  public static readonly int WEBVIEW_HINT_MAX = webviewPINVOKE.WEBVIEW_HINT_MAX_get();
  public static readonly int WEBVIEW_HINT_FIXED = webviewPINVOKE.WEBVIEW_HINT_FIXED_get();
}
