# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _webview
else:
    import _webview

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


WEBVIEW_HINT_NONE = _webview.WEBVIEW_HINT_NONE
WEBVIEW_HINT_MIN = _webview.WEBVIEW_HINT_MIN
WEBVIEW_HINT_MAX = _webview.WEBVIEW_HINT_MAX
WEBVIEW_HINT_FIXED = _webview.WEBVIEW_HINT_FIXED

def webview_create(debug, window):
    return _webview.webview_create(debug, window)

def webview_destroy(w):
    return _webview.webview_destroy(w)

def webview_run(w):
    return _webview.webview_run(w)

def webview_terminate(w):
    return _webview.webview_terminate(w)

def webview_dispatch(w, fn, arg):
    return _webview.webview_dispatch(w, fn, arg)

def webview_get_window(w):
    return _webview.webview_get_window(w)

def webview_set_title(w, title):
    return _webview.webview_set_title(w, title)

def webview_set_size(w, width, height, hints):
    return _webview.webview_set_size(w, width, height, hints)

def webview_navigate(w, url):
    return _webview.webview_navigate(w, url)

def webview_set_html(w, html):
    return _webview.webview_set_html(w, html)

def webview_init(w, js):
    return _webview.webview_init(w, js)

def webview_eval(w, js):
    return _webview.webview_eval(w, js)

def webview_bind(w, name, fn, arg):
    return _webview.webview_bind(w, name, fn, arg)

def webview_unbind(w, name):
    return _webview.webview_unbind(w, name)

def webview_return(w, seq, status, result):
    return _webview.webview_return(w, seq, status, result)


