#ifndef WEBVIEW_EMBEDDED_WEBVIEW2_H
#define WEBVIEW_EMBEDDED_WEBVIEW2_H
#if defined(WEBVIEW_USE_EMBEDDED_WEBVIEW2) && !defined(WEBVIEW_NO_EMBEDDED_WEBVIEW2)
#ifndef WEBVIEW_EMBEDDED_WEBVIEW2_HEADER
#define WEBVIEW_EMBEDDED_WEBVIEW2_HEADER "1.0.1150.38/WebView2.h"
#endif /* WEBVIEW_EMBEDDED_WEBVIEW2_HEADER */
#include WEBVIEW_EMBEDDED_WEBVIEW2_HEADER
#else
#include <WebView2.h>
#endif /* defined(WEBVIEW_USE_EMBEDDED_WEBVIEW2) && !defined(WEBVIEW_NO_EMBEDDED_WEBVIEW2) */
#endif /* WEBVIEW_EMBEDDED_WEBVIEW2_H */
