set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(CMAKE_SYSROOT /usr/i686-w64-mingw32)
set(CMAKE_C_COMPILER "i686-w64-mingw32-gcc${WEBVIEW_TOOLCHAIN_EXECUTABLE_SUFFIX}")
set(CMAKE_CXX_COMPILER "i686-w64-mingw32-g++${WEBVIEW_TOOLCHAIN_EXECUTABLE_SUFFIX}")

find_program(RANLIB_GCC i686-w64-mingw32-gcc-ranlib)
if(NOT RANLIB_GCC)
    set(CMAKE_RANLIB i686-w64-mingw32-ranlib)
else()
    set(CMAKE_RANLIB i686-w64-mingw32-gcc-ranlib)
endif()

find_program(RC_COMPILER_GCC i686-w64-mingw32-gcc-windres)
if(NOT RC_COMPILER_GCC)
    set(CMAKE_RC_COMPILER i686-w64-mingw32-windres)
else()
    set(CMAKE_RC_COMPILER i686-w64-mingw32-gcc-windres)
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
