set(CMAKE_SYSTEM_NAME Darwin)

set(CMAKE_C_COMPILER "clang${WEBVIEW_TOOLCHAIN_EXECUTABLE_SUFFIX}")
set(CMAKE_CXX_COMPILER "clang++${WEBVIEW_TOOLCHAIN_EXECUTABLE_SUFFIX}")

set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64" CACHE INTERNAL "")
