set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_SYSROOT /usr/x86_64-w64-mingw32)
set(CMAKE_C_COMPILER "x86_64-w64-mingw32-gcc${WEBVIEW_TOOLCHAIN_EXECUTABLE_SUFFIX}")
set(CMAKE_CXX_COMPILER "x86_64-w64-mingw32-g++${WEBVIEW_TOOLCHAIN_EXECUTABLE_SUFFIX}")

find_program(RANLIB_GCC x86_64-w64-mingw32-gcc-ranlib)
if(NOT RANLIB_GCC)
    set(CMAKE_RANLIB x86_64-w64-mingw32-ranlib)
else()
    set(CMAKE_RANLIB x86_64-w64-mingw32-gcc-ranlib)
endif()

find_program(RC_COMPILER_GCC x86_64-w64-mingw32-gcc-windres)
if(NOT RC_COMPILER_GCC)
    set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)
else()
    set(CMAKE_RC_COMPILER x86_64-w64-mingw32-gcc-windres)
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
