set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER "gcc${WEBVIEW_TOOLCHAIN_EXECUTABLE_SUFFIX}")
set(CMAKE_CXX_COMPILER "g++${WEBVIEW_TOOLCHAIN_EXECUTABLE_SUFFIX}")

set(MSYSTEM ucrt64 CACHE INTERNAL "")
