set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER "clang${WEBVIEW_TOOLCHAIN_EXECUTABLE_SUFFIX}")
set(CMAKE_CXX_COMPILER "clang++${WEBVIEW_TOOLCHAIN_EXECUTABLE_SUFFIX}")

set(MSYSTEM clang64 CACHE INTERNAL "")
